package ast;

import org.antlr.v4.runtime.Token;

import java.util.Arrays;
import java.util.Objects;

/**
 * The class generated by the asm tool during instrumentation.
 *
 * @author Ben
 */
public class ClassNode extends Node {

  private String name_;
  private byte[] bytes_;

  public ClassNode() {
    this(null, null);
  }

  public ClassNode(final String name, final byte[] bytes) {
    this(null, name, bytes);
  }

  public ClassNode(Token token, final String name, final byte[] bytes) {
    super(token);
    setName(name);
    setBytes(bytes);
  }

  public ClassNode setName(final String name) {
    if (Objects.equals(name, name_)) {
      return this;
    }
    name_ = name;
    return this;
  }

  public String getName() {
    return name_;
  }

  public ClassNode setBytes(final byte[] bytes) {
    if (Arrays.equals(bytes, bytes_)) {
      return this;
    }
    bytes_ = bytes;
    return this;
  }

  public byte[] getBytes() {
    return bytes_;
  }
}
