#!/bin/bash

##############################################################################
##                                                                          ##
##  ProcessJ Group - University of Nevada, Las Vegas                        ##
##                                                                          ##
##  use -classpath just as in java to use a custom classpath                ##
##                                                                          ##
##############################################################################

# make sure we don't continue on if something in this script doesn't work right
# TODO: rewrite this script to use the benefits of set -e -o pipefail while
# still printing errors... if that's possible.
# set -e -o pipefail

homedir=~
eval homedir=$homedir

## configuration file containing path and other resource information
CONFIG_FILE="processjrc"

## working directory for generated Java files
workingdir=""
## install directory for processj source files
installdir=""

############################################################################

## check if configuration file exists
if [ ! -e "$homedir/$CONFIG_FILE" ] ; then
  echo "Missing ProcessJ configuration file."
  echo "The configuration file should be in '$homedir'"
  exit 1
fi

## set configuration file
CONFIG_FILE="$homedir/$CONFIG_FILE"

############################################################################

## check if the processjrc file contains a working directory
if ! grep "workingdir" "$CONFIG_FILE" > /dev/null ; then
    echo "Missing 'workingdir' in '$CONFIG_FILE'"
    exit 1
else
    ## check if the working directory is specified in processjrc
    workingdir="`grep workingdir $CONFIG_FILE | cut -d '=' -f 2 | sed 's/ //g'`"
    if [ -z  "$workingdir" ]; then
        echo "Configuration file must contain a line of the form: 'workingdir=...'"
        exit 1
    fi
fi

## set working directory
workingdir="$homedir/$workingdir"
# echo "working dir is $workingdir"

############################################################################

## check if the working directory exists
if [ ! -d "$workingdir" ] ; then
    echo "Missing working directory '$workingdir'"
    read -p "Do you wish to create '$workingdir'? [y/n] " yn
    case $yn in
        [Yy]* )
            mkdir $workingdir
            chmod 755 $workingdir
            echo "Working directory created";;
        [Nn]* )
            echo "Working directory not created"
            exit;;
        * )
            exit;;
    esac
fi

## clean working directory
rm -i -rf $workingdir/* > /dev/null

############################################################################

## check if the processjrc file contains an install directory
installdir="`grep installdir $CONFIG_FILE | cut -d '=' -f 2 | sed 's/ //g'`"

if [ -z "$installdir" ] ; then
    echo "Configuration file must contain a line of the form: 'installdir=...'"
    exit 1
fi

## set install directory
installdir="$homedir/$installdir"
# echo "installdir is $installdir"

############################################################################

## display usage
if [ "$#" -lt 1 ] ; then
    echo "Illegal number of parameters"
    exit 1
fi

## run the processj compiler
PROCESSJC=`java -cp $installdir/bin:$installdir/resources/jars/java_cup_runtime.jar:$installdir/resources/jars/ST-4.0.7.jar:$installdir/resources/jars/asm-all-5.2.jar:$installdir:$installdir/bin:. ProcessJc -include $installdir/include $@`
# PROCESSJC=`java -cp $installdir/resources/jars/java_cup_runtime.jar:$installdir/resources/jars/ST-4.0.7.jar:$installdir/resources/jars/asm-all-5.2.jar:$installdir:$installdir/bin:. ProcessJc -include $installdir/include $@`
## TODO do silly check for errors
#ERRORS=`echo "${PROCESSJC}" | awk '{print;}'`
ERRORS=`echo "${PROCESSJC}" | awk -v n=1 '{if(NR>n) print a[NR%n]; a[NR%n]=$0}'`
STATUS=`echo "${PROCESSJC}" | awk '/./{line=$0} END{print line}'`

if [ "$STATUS" = "** COMPILATION COMPLETED SUCCESSFULLY **" ] ; then
  echo "$ERRORS"
  echo "ProcessJ compilation successful"
else
  echo "$ERRORS"
  # exit 1
fi

# temporary stop until I get an actual flag somehow that says "oh hey you should
# just generate C++ code and not build the binary"
# exit 0

# TODO: make this generate c++ code
# ---
# need to include the runtime (finally) and make sure that the native libraries
# (i.e. io.hpp) are included

############################################################################
## build the runtime using make
# strip .pj
BINARYFILE=${@%???}
# strip everything but the binary
BINARYFILE=${BINARYFILE##*/}
echo "Compiling binary for $BINARYFILE"
# makefile uses NAME variable to look in builds/ for a .cpp file to build
# ---
# this should change later, but for now it works. will need to redo
# so it's more portable
O=`make build -j6 NAME=$BINARYFILE`
echo ${O}

# workaround to stop after compilation -- we have a binary!
exit 0