package misc;

/**
 * The class generated by the asm tool during instrumentation.
 *
 * @author Ben
 */
public class ProcessJClass {

  private final String name_;
  private final byte[] bytes_;

  public ProcessJClass(final String name, final byte[] bytes) {
    name_ = name;
    bytes_ = bytes;
  }

  public String getName() {
    return name_;
  }

  public byte[] getBytes() {
    return bytes_;
  }
}
