package misc;

import ast.Node;

/**
 * The class generated by the asm tool during instrumentation.
 *
 * @author Ben
 */
public class PJClass extends Node {

  private final String name_;
  private final byte[] bytes_;

  public PJClass(final String name, final byte[] bytes) {
    super(null);
    name_ = name;
    bytes_ = bytes;
  }

  public String getName() {
    return name_;
  }

  public byte[] getBytes() {
    return bytes_;
  }
}
