package utilities;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.Iterator;
import java.util.Stack;

/**
 * This class is used to track down various kind of error/warning
 * messages produced by the ProcessJ compiler at compile-time or
 * runtime.
 * 
 * @author ben
 * @version 21/10/2018
 * @since 1.2
 */
public enum PJBugManager {
    
    INSTANCE;
    
    private static final String OUTFILE_NAME = "PJErrorfile";
    
    /** Number of errors/warning messages generated by the compiler */
    private int errorCount;
    
    /** Last registered message */
    private PJBugMessage postPonedMessage = null;
    
    /** List of errors/warning messages */
    private Stack<PJBugMessage> stackTrace;
    
    /** Input file that contains error/warning messages */
    public String fileName = "";
    
    /** Location of input file */
    public String packageName = "";
    
    PJBugManager() {
        errorCount = 0;
        stackTrace = new Stack<PJBugMessage>();
    }
    
    private void addMessageAndExit(PJBugMessage cm, MessageNumber msg) {
        ErrorSeverity severity = msg.getErrorSeverity();
        switch (severity) {
        case INFO:
        case WARNING:
            break;
        case ERROR:
            ++errorCount;
            break;
        }
        stackTrace.push(cm);
        postPonedMessage = cm;
    }
    
    public void reportMessageAndExit(PJBugMessage pjm, MessageType mt) {
        pjm = Assert.nonNull(pjm, "Compiler error message cannot be 'null'.");
        boolean stop = false;
        addMessageAndExit(pjm, pjm.getMessageNumber());
        
        switch(mt) {
        case PRINT_STOP:
            stop = true;
        case PRINT_CONTINUE:
            // Throw the first error that occurred
            if (postPonedMessage == null)
                postPonedMessage = pjm;
            System.err.println(pjm.getRenderMessage());
            if (stop)
                System.exit(1);
        case DONT_PRINT_CONTINUE:
            break;
        }
    }
    
    public void reportMessage(PJBugMessage pjm) {
        reportMessageAndExit(pjm, pjm.getMessageNumber().getMessageType());
    }
    
    public int getErrorCount() {
        return errorCount;
    }
    
    public Stack<PJBugMessage> getTrace() {
        return stackTrace;
    }
    
    public PJBugMessage postPonedMessage() {
        return postPonedMessage;
    }
    
    public void printTrace(String src) {
        System.out.println("****************************************");
        System.out.println("*         S T A C K - T R A C E        *");
        System.out.println("****************************************");
        System.out.print(errorCount + " error(s) in '" + src + "'");
        Iterator<PJBugMessage> it = stackTrace.iterator();
        while (it.hasNext()) {
            System.out.println(it.next().getRenderMessage());
            if (it.hasNext())
                System.out.println("=======================================================");
        }
    }
    
    public void setPackageName(String name) {
        // First strip the 'Xxx.pj' part
        String str = name.replaceAll("\\.pj$", "");
        // Now remove the absolute path
        String absPath = new File("").getAbsolutePath() + "/";
        str = str.replaceAll(absPath, "");
        // Replace all '/' with '.'
        str = str.replaceAll("/", "\\.");
        packageName = str;
    }
    
    public void setFileName(String name) {
        // Remove all double '//:'
        String str = name.replaceAll("//","/");
        // Now remove the absolute path
        String absPath = new File("").getAbsolutePath() + "/";
        str = str.replaceAll(absPath,"");
        fileName = str;
    }
    
    public void writeBugsToFile(String dir) {
        // Write to current directory if none is provided
        if (dir == null || "".equals(dir))
            dir = new File("").getAbsolutePath() + File.separator;
        String outfile = dir + OUTFILE_NAME + ".txt";
        StringBuilder sb = new StringBuilder();
        for (PJBugMessage msg : stackTrace) {
            sb.append(msg.getMessageNumber().getNumber());
            sb.append("\n");
        }
        Writer writer = null;
        try {
            writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(outfile), "utf-8"));
            writer.write(sb.toString());
            writer.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
