package utilities;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.Iterator;
import java.util.Stack;

/**
 * This class is used to track down various kind of error/warning
 * messages produced by the ProcessJ compiler at compile-time or
 * runtime.
 * 
 * @author ben
 * @version 21/10/2018
 * @since 1.2
 */
public enum PJBugManager {
    
    INSTANCE
    ;
    
    /** Number of errors/warning messages generated by the compiler */
    private int errorCount;
    
    /** Last registered message */
    private PJBugMessage postPonedMessage = null;
    
    /** List of errors/warning messages */
    private Stack<PJBugMessage> stackTrace;
    
    /** Input file that contains error/warning messages */
    public String fileName = "";
    
    /** Location of input file */
    public String packageName = "";
    
    PJBugManager() {
        errorCount = 0;
        stackTrace = new Stack<PJBugMessage>();
    }
    
    public void addMessageAndExit(PJBugMessage cm, MessageNumber msg) {
        ErrorSeverity severity = msg.getErrorSeverity();
        switch (severity) {
        case INFO:
        case WARNING:
            break;
        case ERROR:
            ++errorCount;
            break;
        }
        stackTrace.push(cm);
        postPonedMessage = cm;
    }
    
    public void reportMessageAndExit(PJBugMessage pjm, MessageType mt) {
        pjm = Assert.nonNull(pjm, "Compiler message cannot be null.");
        boolean stop = false;
        addMessageAndExit(pjm, pjm.getMessageNumber());
        
        switch(mt) {
        case PRINT_STOP:
            stop = true;
        case PRINT_CONTINUE:
            /* Throw the first error that occurred */
            if (postPonedMessage == null)
                postPonedMessage = pjm;
            System.out.println(pjm.getRenderMessage());
            if (stop)
                System.exit(1);
        case DONT_PRINT_CONTINUE:
            break;
        }
    }
    
    public void reportMessage(PJBugMessage pjm) {
        reportMessageAndExit(pjm, pjm.getMessageNumber().getMessageType());
    }
    
    public int getErrorCount() {
        return errorCount;
    }
    
    public Stack<PJBugMessage> getTrace() {
        return stackTrace;
    }
    
    public PJBugMessage postPonedMessage() {
        return postPonedMessage;
    }
    
    public void printTrace(String src) {
        System.out.println("****************************************");
        System.out.println("*         S T A C K  T R A C E         *");
        System.out.println("****************************************");
        System.out.print(errorCount + " error(s) in '" + src + "'");
        Iterator<PJBugMessage> it = stackTrace.iterator();
        while (it.hasNext()) {
            System.out.println(it.next().getRenderMessage());
            if (it.hasNext())
                System.out.println("=======================================================");
        }
    }
    
    public void setPackageName(String name) {
        /** First strip the 'Xxx.pj' part */
        String str = name.replaceAll("\\.pj$", "");
        /** Now remove the absolute path */
        String absPath = new File("").getAbsolutePath() + "/";
        str = str.replaceAll(absPath, "");
        /** Replace all '/' with */
        str = str.replaceAll("/", "\\.");
        packageName = str;
    }
    
    public void setFileName(String name) {
        /** Remove all double '//:' */
        String str = name.replaceAll("//","/");
        /** Now remove the absolute path */
        String absPath = new File("").getAbsolutePath() + "/";
        str = str.replaceAll(absPath,"");
        fileName = str;
    }
    
    public void writeErrorToFile(String outputFile) {
        /** TODO: Should the error file be written to the source directory? */
        String javafile = "/Users/Ben/Documents/" + outputFile + ".txt";
        StringBuilder stringBuilder = new StringBuilder();
        for (PJBugMessage cm : stackTrace)
            stringBuilder.append(cm.getMessageNumber().getNumber()).append("\n");
        Writer writer = null;
        try {
            writer = new BufferedWriter(new OutputStreamWriter(new FileOutputStream(javafile), "utf-8"));
            writer.write(stringBuilder.toString());
            writer.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }
}
