package analysischecker;

import ast.Token;

/**
 * Concrete node for syntax-errors generated by CUP/flex.
 * 
 * @author ben
 */
public abstract class ASTNode {
    
    public abstract int size();
    
    public abstract ASTNode get(int index);
    
    public abstract Token getRoot();
    
    public abstract ReductionNode asReduction();
    
    public String getText() {
        return getRoot().getText();
    }
    
    public int getStartLine() {
        return getRoot().getStartLine();
    }

    public int getStartColumn() {
        return getRoot().getStartColumn();
    }
    
    public boolean isEmpty() {
        return false;
    }
    
    public int children() {
        int num = size();
        if (num > 1)
            return num - 1;
        return 0;
    }
    
    public boolean hasChildren() {
        return (children() > 0);
    }
    
    public String getRootText() {
        Token root = getRoot();
        return root.getText();
    }
    
    public ASTNode add(ASTNode n) {
        throw new AssertionError("'addNode()' is not supported for this type of node");
    }
    
    public ASTNode remove(int index) {
        throw new AssertionError("'remove()' is not supported for this type of node");
    }
    
    public ASTNode set(int index, ASTNode n) {
        throw new AssertionError("'setNode()' is not supported for this type of node");
    }
    
    public void addChildrenOf(ASTNode n) {
        for (int i = 1; i < n.size(); ++i)
            add(n.get(i));
    }
    
    public ASTNode endNode() {
        throw new AssertionError("'endNode()' is not supported for this type of node");
    }
    
    public void print() {
        Token root = getRoot();
        System.out.print(root.getText() + " ");
        if (children() > 0) {
            int count = size();
            for (int i = 1; i < count; ++i)
                System.out.print(get(i).getText() + " ");
        }
    }
    
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        Token root = getRoot();
        sb.append(root.getText());
        sb.append(" ");
        if (children() > 0) {
            int count = size();
            for (int i = 1; i < count; ++i) {
                sb.append(get(i).getText());
                sb.append(" ");
            }
        }
        return sb.toString();
    }
}
