#include <runtime/pj_runtime.hpp>
#include <functional>
#include <std/io.hpp>
#include <std/math.hpp>
#include <std/random.hpp>



/**
 * File generated by the ProcessJ Compiler.
 * Package name 'tests'.
 * Code generation for 'enrolledtest.pj'.
 * Target class 'enrolledtest'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas.
 */

class _proc$foo01198 : public pj_runtime::pj_process
{

public:
    _proc$foo01198() = delete;
    _proc$foo01198(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_barrier* _pd$b1)
    : id(id)
    {
        this->sched = sched;
        this->_pd$b1 = _pd$b1;
    }

    virtual ~_proc$foo01198() = default;

    virtual void run()
    { 

        // local variables
        switch (get_label())
        {
            case 0: goto _proc$foo01198L0; break;
            case 1: goto _proc$foo01198L1; break;
        }

        _proc$foo01198L0:

        _pd$b1->sync(this);
        this->set_label(1);
        // yield();
        return;
        _proc$foo01198L1:
        io::println("done sync'ing foo");
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_barrier* _pd$b1;
private:
    int32_t id;
    pj_runtime::pj_scheduler* sched;
};


class _proc$bar11198 : public pj_runtime::pj_process
{

public:
    _proc$bar11198() = delete;
    _proc$bar11198(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_barrier* _pd$b2)
    : id(id)
    {
        this->sched = sched;
        this->_pd$b2 = _pd$b2;
    }

    virtual ~_proc$bar11198() = default;

    virtual void run()
    { 

        // local variables
        switch (get_label())
        {
            case 0: goto _proc$bar11198L0; break;
            case 1: goto _proc$bar11198L1; break;
        }

        _proc$bar11198L0:

        _pd$b2->sync(this);
        this->set_label(1);
        // yield();
        return;
        _proc$bar11198L1:
        io::println("done sync'ing bar");
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_barrier* _pd$b2;
private:
    int32_t id;
    pj_runtime::pj_scheduler* sched;
};


class _proc$baz21198 : public pj_runtime::pj_process
{

public:
    _proc$baz21198() = delete;
    _proc$baz21198(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_barrier* _pd$b3)
    : id(id)
    {
        this->sched = sched;
        this->_pd$b3 = _pd$b3;
    }

    virtual ~_proc$baz21198() = default;

    virtual void run()
    { 

        // local variables
        switch (get_label())
        {
            case 0: goto _proc$baz21198L0; break;
            case 1: goto _proc$baz21198L1; break;
        }

        _proc$baz21198L0:

        _pd$b3->sync(this);
        this->set_label(1);
        // yield();
        return;
        _proc$baz21198L1:
        io::println("done sync'ing baz");
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_barrier* _pd$b3;
private:
    int32_t id;
    pj_runtime::pj_scheduler* sched;
};


static void _method$f30()
{
}

class _proc$main41169311 : public pj_runtime::pj_process
{

public:
    _proc$main41169311() = delete;
    _proc$main41169311(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args4)
    : id(id)
    {
        this->sched = sched;
        this->_pd$args4 = _pd$args4;
    }

    virtual ~_proc$main41169311() = default;

    virtual void run()
    { 

        // local variables
        static pj_runtime::pj_barrier* _ld$b1;
        static pj_runtime::pj_par* _ld$_par1;
        static pj_runtime::pj_par* _ld$_par2;

        switch (get_label())
        {
            case 0: goto _proc$main41169311L0; break;
            case 1: goto _proc$main41169311L1; break;
        }

        _proc$main41169311L0:

        _ld$b1 = static_cast<pj_runtime::pj_barrier*>(0);
        _ld$_par1 = static_cast<pj_runtime::pj_par*>(0);
        _ld$_par2 = static_cast<pj_runtime::pj_par*>(0);

        _ld$b1 = new pj_runtime::pj_barrier();
        _ld$_par1 = new pj_runtime::pj_par(3, this);

         static std::function _proc$Anonymous50__ld$_par1_decrement = [this]() { _ld$_par1->decrement(); };
        class _proc$Anonymous50 : public pj_runtime::pj_process
        {
        public:
            _proc$Anonymous50() = delete;
            _proc$Anonymous50(int32_t                      id,
                              pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args4)
            : id(id)
            {
                this->sched = sched;
                this->_pd$args4 = _pd$args4;
            }

            virtual ~_proc$Anonymous50() = default;

            virtual void run()
            {
                switch (get_label())
                {
                    case 0: goto _proc$Anonymous50L0; break;
                    case 1: goto _proc$Anonymous50L1; break;
                }

                _proc$Anonymous50L0:

                _ld$_par2 = new pj_runtime::pj_par(3, this);
                _ld$b1->enroll(3);

                 // THIS DOES NOT WORK WITH C++ (InvocationProcType)
                static std::function _proc$foo01198__ld$_par2_decrement = [this]() { _ld$_par2->decrement(); };
                class _proc$foo01198_overload_finalize : public _proc$foo01198
                {
                public:
                    _proc$foo01198_overload_finalize(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_barrier* b)
                    : _proc$foo01198{id, sched, b}
                    {

                    }

                    // my vars are pj_runtime::pj_barrier* b
                    virtual void finalize()
                    {
                        std::cout << "foo decrementing par2" << std::endl;
                        _proc$foo01198__ld$_par2_decrement();
                        std::cout << "foo resigning from b" << std::endl;
                        _ld$b1->resign();
                    }
                };

                this->sched->insert(new _proc$foo01198_overload_finalize(this->id + 6, this->sched, _ld$b1));

                 // THIS DOES NOT WORK WITH C++ (InvocationProcType)
                static std::function _proc$bar11198__ld$_par2_decrement = [this]() { _ld$_par2->decrement(); };
                class _proc$bar11198_overload_finalize : public _proc$bar11198
                {
                public:
                    _proc$bar11198_overload_finalize(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_barrier* b)
                    : _proc$bar11198{id, sched, b}
                    {

                    }

                    // my vars are pj_runtime::pj_barrier* b
                    virtual void finalize()
                    {
                        std::cout << "bar decrementing par2" << std::endl;
                        _proc$bar11198__ld$_par2_decrement();
                        std::cout << "bar resigning from b" << std::endl;
                        _ld$b1->resign();
                    }
                };

                this->sched->insert(new _proc$bar11198_overload_finalize(this->id + 7, this->sched, _ld$b1));

                 // THIS DOES NOT WORK WITH C++ (InvocationProcType)
                static std::function _proc$baz21198__ld$_par2_decrement = [this]() { _ld$_par2->decrement(); };
                class _proc$baz21198_overload_finalize : public _proc$baz21198
                {
                public:
                    _proc$baz21198_overload_finalize(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_barrier* b)
                    : _proc$baz21198{id, sched, b}
                    {

                    }

                    // my vars are pj_runtime::pj_barrier* b
                    virtual void finalize()
                    {
                        std::cout << "baz decrementing par2" << std::endl;
                        _proc$baz21198__ld$_par2_decrement();
                        std::cout << "baz resigning from b" << std::endl;
                        _ld$b1->resign();
                    }
                };

                this->sched->insert(new _proc$baz21198_overload_finalize(this->id + 5, this->sched, _ld$b1));

                if (_ld$_par2->should_yield()) {
                    this->set_label(1);
                    return;
                }

                _proc$Anonymous50L1:
                delete _ld$_par2;
                std::cout << "end of par process\n";
                terminate();
            }
            virtual void finalize()
            {
                std::cout << "par2 process decrementing par1" << std::endl;
                _proc$Anonymous50__ld$_par1_decrement();
                // std::cout << "par2 process resigning from b" << std::endl;
                // _ld$b1->resign();
            }
        protected:
            pj_runtime::pj_array<std::string>* _pd$args4;

        private:
            int32_t id;
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous50(this->id + 8, this->sched, _pd$args4));

         static std::function _proc$Anonymous60__ld$_par1_decrement = [this]() { _ld$_par1->decrement(); };
        class _proc$Anonymous60 : public pj_runtime::pj_process
        {
        public:
            _proc$Anonymous60() = delete;
            _proc$Anonymous60(int32_t                      id,
                              pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args4)
            : id(id)
            {
                this->sched = sched;
                this->_pd$args4 = _pd$args4;
            }

            virtual ~_proc$Anonymous60() = default;

            virtual void run()
            {
                _method$f30();
                terminate();
            }
            virtual void finalize()
            {
                std::cout << "method invocation f1 decrementing par1" << std::endl;
                _proc$Anonymous60__ld$_par1_decrement();
                // std::cout << "method invocation f1 resigning from b" << std::endl;
                // _ld$b1->resign();
            }
        protected:
            pj_runtime::pj_array<std::string>* _pd$args4;

        private:
            int32_t id;
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous60(this->id + 9, this->sched, _pd$args4));

         static std::function _proc$Anonymous70__ld$_par1_decrement = [this]() { _ld$_par1->decrement(); };
        class _proc$Anonymous70 : public pj_runtime::pj_process
        {
        public:
            _proc$Anonymous70() = delete;
            _proc$Anonymous70(int32_t                      id,
                              pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args4)
            : id(id)
            {
                this->sched = sched;
                this->_pd$args4 = _pd$args4;
            }

            virtual ~_proc$Anonymous70() = default;

            virtual void run()
            {
                _method$f30();
                terminate();
            }
            virtual void finalize()
            {
                std::cout << "method invocation f2 decrementing par1" << std::endl;
                _proc$Anonymous70__ld$_par1_decrement();
                // std::cout << "method invocation f2 resigning from b" << std::endl;
                // _ld$b1->resign();
            }
        protected:
            pj_runtime::pj_array<std::string>* _pd$args4;

        private:
            int32_t id;
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous70(this->id + 10, this->sched, _pd$args4));

        if (_ld$_par1->should_yield()) {
            this->set_label(1);
            return;
        }

        _proc$main41169311L1:
        delete _ld$_par1;
        delete _ld$b1;
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_array<std::string>* _pd$args4;
private:
    int32_t id;
    pj_runtime::pj_scheduler* sched;
};


int main(int argc, char* argv[])
{
    std::cout << "\n *** CREATING SCHEDULER *** \n\n";
    pj_runtime::pj_scheduler sched;

    std::cout << "\n *** CREATING MAIN PROCESS *** \n\n";

    pj_runtime::pj_array<std::string> args(argc);
    for(int i = 0; i < argc; ++i)
    {
        args[i] = argv[i];
    }

    _proc$main41169311* main_proc = new _proc$main41169311(0, &sched, &args);

    std::cout << "\n *** SCHEDULING MAIN PROCESS *** \n\n";
    sched.insert(main_proc);

    std::cout << "\n *** STARTING SCHEDULER *** \n\n";
    sched.start();
}
