#include <runtime/pj_runtime.hpp>
#include <functional>
#include <std/io.hpp>
#include <std/math.hpp>
#include <std/random.hpp>



/**
 * File generated by the ProcessJ Compiler.
 * Package name 'tests'.
 * Code generation for 'Hello.pj'.
 * Target class 'Hello'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas.
 */

static void _method$foo00()
{
}

static void _method$bar10()
{
}

class _proc$main21169311 : public pj_runtime::pj_process
{

public:
    _proc$main21169311() = delete;
    _proc$main21169311(int32_t id, pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args1)
    : id(id)
    {
        this->sched = sched;
        this->_pd$args1 = _pd$args1;
    }

    virtual ~_proc$main21169311() = default;

    virtual void run()
    { 

        // local variables
        static pj_runtime::pj_par* _ld$_par1;

        switch (get_label())
        {
            case 0: goto _proc$main21169311L0; break;
            case 1: goto _proc$main21169311L1; break;
        }

        _proc$main21169311L0:

        _ld$_par1 = static_cast<pj_runtime::pj_par*>(0);

        _ld$_par1 = new pj_runtime::pj_par(3, this);

         static std::function _proc$Anonymous30__ld$_par1_decrement = [this]() { _ld$_par1->decrement(); };
        class _proc$Anonymous30 : public pj_runtime::pj_process
        {
        public:
            _proc$Anonymous30() = delete;
            _proc$Anonymous30(int32_t                      id,
                              pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args1)
            : id(id)
            {
                this->sched = sched;
                this->_pd$args1 = _pd$args1;
            }

            virtual ~_proc$Anonymous30() = default;

            virtual void run()
            {
                io::println("Print from Hello");
                terminate();
            }
            virtual void finalize()
            {
                _proc$Anonymous30__ld$_par1_decrement();
            }
        protected:
            pj_runtime::pj_array<std::string>* _pd$args1;

        private:
            int32_t id;
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous30(this->id + 3, this->sched, _pd$args1));

         static std::function _proc$Anonymous40__ld$_par1_decrement = [this]() { _ld$_par1->decrement(); };
        class _proc$Anonymous40 : public pj_runtime::pj_process
        {
        public:
            _proc$Anonymous40() = delete;
            _proc$Anonymous40(int32_t                      id,
                              pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args1)
            : id(id)
            {
                this->sched = sched;
                this->_pd$args1 = _pd$args1;
            }

            virtual ~_proc$Anonymous40() = default;

            virtual void run()
            {
                _method$foo00();
                terminate();
            }
            virtual void finalize()
            {
                _proc$Anonymous40__ld$_par1_decrement();
            }
        protected:
            pj_runtime::pj_array<std::string>* _pd$args1;

        private:
            int32_t id;
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous40(this->id + 4, this->sched, _pd$args1));

         static std::function _proc$Anonymous50__ld$_par1_decrement = [this]() { _ld$_par1->decrement(); };
        class _proc$Anonymous50 : public pj_runtime::pj_process
        {
        public:
            _proc$Anonymous50() = delete;
            _proc$Anonymous50(int32_t                      id,
                              pj_runtime::pj_scheduler* sched, pj_runtime::pj_array<std::string>* _pd$args1)
            : id(id)
            {
                this->sched = sched;
                this->_pd$args1 = _pd$args1;
            }

            virtual ~_proc$Anonymous50() = default;

            virtual void run()
            {
                _method$bar10();
                terminate();
            }
            virtual void finalize()
            {
                _proc$Anonymous50__ld$_par1_decrement();
            }
        protected:
            pj_runtime::pj_array<std::string>* _pd$args1;

        private:
            int32_t id;
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous50(this->id + 5, this->sched, _pd$args1));

        if (_ld$_par1->should_yield()) {
            this->set_label(1);
            return;
        }

        _proc$main21169311L1:
        delete _ld$_par1;
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_array<std::string>* _pd$args1;
private:
    int32_t id;
    pj_runtime::pj_scheduler* sched;
};


int main(int argc, char* argv[])
{
    std::cout << "\n *** CREATING SCHEDULER *** \n\n";
    pj_runtime::pj_scheduler sched;

    std::cout << "\n *** CREATING MAIN PROCESS *** \n\n";

    pj_runtime::pj_array<std::string> args(argc);
    for(int i = 0; i < argc; ++i)
    {
        args[i] = argv[i];
    }

    _proc$main21169311* main_proc = new _proc$main21169311(0, &sched, &args);

    std::cout << "\n *** SCHEDULING MAIN PROCESS *** \n\n";
    sched.insert(main_proc);

    std::cout << "\n *** STARTING SCHEDULER *** \n\n";
    sched.start();
}
