#include <runtime/pj_runtime.hpp>
#include <functional>
#include <std/io.hpp>


/**
 * File generated by the ProcessJ Compiler.
 * Package name 'tests'.
 * Code generation for 'proctest.pj'.
 * Target class 'proctest'.
 *
 * @author ProcessJ Group - University of Nevada, Las Vegas.
 */

class _proc$foo0$682474553 : public pj_runtime::pj_process
{

public:

    int _ld$x1;
    pj_runtime::pj_par* _ld$_par1;

    _proc$foo0$682474553() = delete;
    _proc$foo0$682474553(pj_runtime::pj_scheduler* sched,
	pj_runtime::pj_one2one_channel<int32_t>* _pd$c11,
	pj_runtime::pj_one2one_channel<int32_t>* _pd$c22)
    {
        this->sched = sched;
        this->_pd$c11 = _pd$c11;
        this->_pd$c22 = _pd$c22;
    }

    virtual ~_proc$foo0$682474553() = default;

    virtual void run()
    { 
        switch (get_label())
        {
            case 0: goto _proc$foo0$682474553L0; break;
            case 1: goto _proc$foo0$682474553L1; break;
        }

        _proc$foo0$682474553L0:

        _ld$x1 = static_cast<int>(0);
        _ld$_par1 = new pj_runtime::pj_par(2, this);

        // my parent class is _proc$foo0$682474553
        class _proc$Anonymous10 : public pj_runtime::pj_process
        {
        public:
            _proc$foo0$682474553* parent;

            _proc$Anonymous10() = delete;
            _proc$Anonymous10(pj_runtime::pj_scheduler* sched,
        	pj_runtime::pj_one2one_channel<int32_t>* _pd$c11,
        pj_runtime::pj_one2one_channel<int32_t>* _pd$c22,
        	_proc$foo0$682474553* parent)
            {
                this->sched = sched;
                this->parent = parent;
                this->_pd$c11 = _pd$c11;
                this->_pd$c22 = _pd$c22;
            }

            virtual ~_proc$Anonymous10() = default;

            virtual void run()
            {
                switch (get_label())
                {
                    case 0: goto _proc$Anonymous10L0; break;
                    case 1: goto _proc$Anonymous10L1; break;
                    case 2: goto _proc$Anonymous10L2; break;
                }

                _proc$Anonymous10L0:

                // i'm a channel read, and my procName is _proc$Anonymous10
                if (!parent->_pd$c11->is_ready_to_read(this)) {
                    this->set_label(1);
                    // yield();
                    return;
                }

                _proc$Anonymous10L1:
                parent->_ld$x1 = parent->_pd$c11->read(this);

                _proc$Anonymous10L2:
                terminate();
            }
            virtual void finalize()
            {
                parent->_ld$_par1->decrement();

            }
        protected:
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c11;
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c22;

        private:
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous10(this->sched, _pd$c11, _pd$c22, this));

        // my parent class is _proc$foo0$682474553
        class _proc$Anonymous20 : public pj_runtime::pj_process
        {
        public:
            _proc$foo0$682474553* parent;

            _proc$Anonymous20() = delete;
            _proc$Anonymous20(pj_runtime::pj_scheduler* sched,
        	pj_runtime::pj_one2one_channel<int32_t>* _pd$c11,
        pj_runtime::pj_one2one_channel<int32_t>* _pd$c22,
        	_proc$foo0$682474553* parent)
            {
                this->sched = sched;
                this->parent = parent;
                this->_pd$c11 = _pd$c11;
                this->_pd$c22 = _pd$c22;
            }

            virtual ~_proc$Anonymous20() = default;

            virtual void run()
            {
                switch (get_label())
                {
                    case 0: goto _proc$Anonymous20L0; break;
                    case 1: goto _proc$Anonymous20L1; break;
                }

                _proc$Anonymous20L0:

                parent->_pd$c22->write(this, 10);
                this->set_label(1);
                // yield();
                return;

                _proc$Anonymous20L1:
                terminate();
            }
            virtual void finalize()
            {
                parent->_ld$_par1->decrement();

            }
        protected:
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c11;
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c22;

        private:
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous20(this->sched, _pd$c11, _pd$c22, this));

        if (_ld$_par1->should_yield()) {
            this->set_label(1);
            return;
        }

        _proc$foo0$682474553L1:
        delete _ld$_par1;
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_one2one_channel<int32_t>* _pd$c11;
    pj_runtime::pj_one2one_channel<int32_t>* _pd$c22;
private:
    pj_runtime::pj_scheduler* sched;
};


class _proc$bar3$539328953 : public pj_runtime::pj_process
{

public:

    int _ld$y2;
    pj_runtime::pj_par* _ld$_par2;

    _proc$bar3$539328953() = delete;
    _proc$bar3$539328953(pj_runtime::pj_scheduler* sched,
	pj_runtime::pj_one2one_channel<int32_t>* _pd$c13,
	pj_runtime::pj_one2one_channel<int32_t>* _pd$c24)
    {
        this->sched = sched;
        this->_pd$c13 = _pd$c13;
        this->_pd$c24 = _pd$c24;
    }

    virtual ~_proc$bar3$539328953() = default;

    virtual void run()
    { 
        switch (get_label())
        {
            case 0: goto _proc$bar3$539328953L0; break;
            case 1: goto _proc$bar3$539328953L1; break;
        }

        _proc$bar3$539328953L0:

        _ld$y2 = static_cast<int>(0);
        _ld$_par2 = new pj_runtime::pj_par(2, this);

        // my parent class is _proc$bar3$539328953
        class _proc$Anonymous40 : public pj_runtime::pj_process
        {
        public:
            _proc$bar3$539328953* parent;

            _proc$Anonymous40() = delete;
            _proc$Anonymous40(pj_runtime::pj_scheduler* sched,
        	pj_runtime::pj_one2one_channel<int32_t>* _pd$c13,
        pj_runtime::pj_one2one_channel<int32_t>* _pd$c24,
        	_proc$bar3$539328953* parent)
            {
                this->sched = sched;
                this->parent = parent;
                this->_pd$c13 = _pd$c13;
                this->_pd$c24 = _pd$c24;
            }

            virtual ~_proc$Anonymous40() = default;

            virtual void run()
            {
                switch (get_label())
                {
                    case 0: goto _proc$Anonymous40L0; break;
                    case 1: goto _proc$Anonymous40L1; break;
                    case 2: goto _proc$Anonymous40L2; break;
                }

                _proc$Anonymous40L0:

                // i'm a channel read, and my procName is _proc$Anonymous40
                if (!parent->_pd$c24->is_ready_to_read(this)) {
                    this->set_label(1);
                    // yield();
                    return;
                }

                _proc$Anonymous40L1:
                parent->_ld$y2 = parent->_pd$c24->read(this);

                _proc$Anonymous40L2:
                terminate();
            }
            virtual void finalize()
            {
                parent->_ld$_par2->decrement();

            }
        protected:
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c13;
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c24;

        private:
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous40(this->sched, _pd$c13, _pd$c24, this));

        // my parent class is _proc$bar3$539328953
        class _proc$Anonymous50 : public pj_runtime::pj_process
        {
        public:
            _proc$bar3$539328953* parent;

            _proc$Anonymous50() = delete;
            _proc$Anonymous50(pj_runtime::pj_scheduler* sched,
        	pj_runtime::pj_one2one_channel<int32_t>* _pd$c13,
        pj_runtime::pj_one2one_channel<int32_t>* _pd$c24,
        	_proc$bar3$539328953* parent)
            {
                this->sched = sched;
                this->parent = parent;
                this->_pd$c13 = _pd$c13;
                this->_pd$c24 = _pd$c24;
            }

            virtual ~_proc$Anonymous50() = default;

            virtual void run()
            {
                switch (get_label())
                {
                    case 0: goto _proc$Anonymous50L0; break;
                    case 1: goto _proc$Anonymous50L1; break;
                }

                _proc$Anonymous50L0:

                parent->_pd$c13->write(this, 20);
                this->set_label(1);
                // yield();
                return;

                _proc$Anonymous50L1:
                terminate();
            }
            virtual void finalize()
            {
                parent->_ld$_par2->decrement();

            }
        protected:
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c13;
            pj_runtime::pj_one2one_channel<int32_t>* _pd$c24;

        private:
            pj_runtime::pj_scheduler* sched;
        };

        this->sched->insert(new _proc$Anonymous50(this->sched, _pd$c13, _pd$c24, this));

        if (_ld$_par2->should_yield()) {
            this->set_label(1);
            return;
        }

        _proc$bar3$539328953L1:
        delete _ld$_par2;
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_one2one_channel<int32_t>* _pd$c13;
    pj_runtime::pj_one2one_channel<int32_t>* _pd$c24;
private:
    pj_runtime::pj_scheduler* sched;
};


class _proc$main61169311 : public pj_runtime::pj_process
{

public:

    int _ld$i3;
    pj_runtime::pj_one2one_channel<int32_t>* _ld$c14;
    pj_runtime::pj_one2one_channel<int32_t>* _ld$c25;
    pj_runtime::pj_par* _ld$_par3;
    std::vector<pj_runtime::pj_process*> par_procs;
    int count;

    _proc$main61169311() = delete;
    _proc$main61169311(pj_runtime::pj_scheduler* sched,
	pj_runtime::pj_array<std::string>* _pd$args5)
    {
        this->sched = sched;
        this->_pd$args5 = _pd$args5;
    }

    virtual ~_proc$main61169311() = default;

    virtual void run()
    { 
        switch (get_label())
        {
            case 0: goto _proc$main61169311L0; break;
            case 1: goto _proc$main61169311L1; break;
        }

        _proc$main61169311L0:
        _ld$_par3 = new pj_runtime::pj_par(0, this);
        count = 0;

          // THIS DOES NOT WORK WITH C++ (InvocationProcType)
         class _proc$foo0$682474553_overload_finalize_0 : public _proc$foo0$682474553
         {
         public:
             _proc$main61169311* parent;

             _proc$foo0$682474553_overload_finalize_0(pj_runtime::pj_scheduler* sched, pj_runtime::pj_one2one_channel<int32_t>* c1, pj_runtime::pj_one2one_channel<int32_t>* c2, _proc$main61169311* parent)
             : _proc$foo0$682474553{sched, c1, c2}, parent(parent)
             {
             }

             // my vars are pj_runtime::pj_one2one_channel<int32_t>* c1, pj_runtime::pj_one2one_channel<int32_t>* c2
             virtual void finalize()
             {
                 parent->_ld$_par3->decrement();
             }
         };
             // this->sched->insert(new _proc$foo0$682474553_overload_finalize_0(this->sched, _ld$c14, _ld$c25, this));
             // this->sched->insert(new _proc$bar3$539328953_overload_finalize_1(this->sched, _ld$c14, _ld$c25, this));

          // THIS DOES NOT WORK WITH C++ (InvocationProcType)
         class _proc$bar3$539328953_overload_finalize_1 : public _proc$bar3$539328953
         {
         public:
             _proc$main61169311* parent;

             _proc$bar3$539328953_overload_finalize_1(pj_runtime::pj_scheduler* sched, pj_runtime::pj_one2one_channel<int32_t>* c1, pj_runtime::pj_one2one_channel<int32_t>* c2, _proc$main61169311* parent)
             : _proc$bar3$539328953{sched, c1, c2}, parent(parent)
             {
             }

             // my vars are pj_runtime::pj_one2one_channel<int32_t>* c1, pj_runtime::pj_one2one_channel<int32_t>* c2
             virtual void finalize()
             {
                 parent->_ld$_par3->decrement();
             }
         };

        for (_ld$i3 = 0; _ld$i3 < 10000000; ++_ld$i3) {
             _ld$c14 = new pj_runtime::pj_one2one_channel<int32_t>();
             _ld$c25 = new pj_runtime::pj_one2one_channel<int32_t>();
             ++count;
             par_procs.push_back(new _proc$foo0$682474553_overload_finalize_0(this->sched, _ld$c14, _ld$c25, this));
             ++count;
             par_procs.push_back(new _proc$bar3$539328953_overload_finalize_1(this->sched, _ld$c14, _ld$c25, this));
         }

         _ld$_par3->set_process_count(count);

         for(_ld$i3 = 0; _ld$i3 < count; ++_ld$i3) {
            sched->insert(par_procs[_ld$i3]);
         }

         if (_ld$_par3->should_yield()) {
             this->set_label(1);
             return;
         }

         _proc$main61169311L1:
         delete _ld$_par3;

        if (_ld$c14) { delete _ld$c14; }
        if (_ld$c25) { delete _ld$c25; }
        terminate();
        return;
    }

protected:
    // formal variables
    pj_runtime::pj_array<std::string>* _pd$args5;
private:
    pj_runtime::pj_scheduler* sched;
};


int main(int argc, char* argv[])
{
    std::cout << "\n *** CREATING SCHEDULER *** \n\n";
    pj_runtime::pj_scheduler sched;

    std::cout << "\n *** CREATING MAIN PROCESS *** \n\n";

    pj_runtime::pj_array<std::string> args(argc);
    for(int i = 0; i < argc; ++i)
    {
        args[i] = argv[i];
    }

    _proc$main61169311* main_proc = new _proc$main61169311(&sched, &args);

    std::cout << "\n *** SCHEDULING MAIN PROCESS *** \n\n";
    sched.insert(main_proc);

    std::cout << "\n *** STARTING SCHEDULER *** \n\n";
    sched.start();
}
