package syntax;

/**
 * Abstract node for syntax-errors generated by CUP or flex.
 * 
 * @author ben
 */
public abstract class ASTSyntaxNode {
    
    private int rowNum = -1;
    private int colNum = -1;
    private int rowNumLast = -1;
    private int colNumLast = -1;
    
    public String text() {
        return "EMPTY (not implemented yet!)";
    }
    
    public int rowNum() {
        return rowNum;
    }
    
    public int colNum() {
        return colNum;
    }
    
    public int rowNumLast() {
        return rowNumLast;
    }
    
    public int colNumLast() {
        return colNumLast;
    }
    
    public void rowNum(int rowNum) {
        this.rowNum = rowNum;
    }
    
    public void colNum(int colNum) {
        this.colNum = colNum;
    }
    
    public void rowNumLast(int rowNumLast) {
        this.rowNumLast = rowNumLast;
    }
    
    public void colNumLast(int colNumLast) {
        this.colNumLast = colNumLast;
    }
    
    public void setNode(ASTSyntaxNode n) {
        rowNum = n.rowNum;
        colNum = n.colNum;
        rowNumLast = n.rowNumLast;
        colNumLast = n.colNumLast;
    }
}
